### ISSUE TITLE
Facing scrypt node error during start

### ISSUE THREAD

**Issue by navinthenapster** [DAVFoundation/dav-cli#29]
Error: The module '/usr/local/lib/node_modules/dav-cli/node_modules/scrypt/build/Release
I have installed the dav-cli but facing scrypt build error when trying to start the server

/scrypt.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/dav-cli/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/dav-cli/node_modules/scrypt.js/node.js:1:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by navinthenapster** [comment]
have tried to rebuild with node 6,7,8,9 using nvm. but still facing this error

**Comment by navinthenapster** [comment]
tried 
$ node bin/dav-cli.js --start to fixed it.
sometimes it works
after reinstalling scrypt and 
node-gy rebuild

**Comment by navinthenapster** [comment]
Problem Found : it is because of scrypt package issue , when installing 
$ npm install scrypt 
it runs the scripts to build ( scrypt/build/Release/scrypt.node) , it uses envirnoment path of node (usr/bin/node) from system .
In case of nvm, it locates at (~/.nvm/versions/v9.11.1/src/node) check if the usr/bin/node is desired version if not , use 
nodepath=$(which node); sudo ln -s $nodepath /usr/bin/node

it creates the sysmlink in case of linux. 

In  case of permission deny .. 
sudo sudo npm install
