### ISSUE TITLE
NPM Install fails under windows

### ISSUE THREAD

**Issue by looeee** [DAVFoundation/dav-cli#32]
## Expected Behavior

npm install -g dav-cli should work under Windows. 

## Current Behavior

Lots of error messages!

```
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 preinstall C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\scrypt
> node node-scrypt-preinstall.js

C:\Users\looee\AppData\Roaming\npm\dav-cli -> C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\bin\dav-cli.js

> keccak@1.4.0 install C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\keccak
> npm run rebuild || echo "Keccak bindings compilation fail. Pure JS implementation will be used."


> keccak@1.4.0 rebuild C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\keccak
> node-gyp rebuild


C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\keccak>if not defined npm_config_node_gyp (node "C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\looee\AppData\Local\Programs\Python\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\looee\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\keccak
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\looee\AppData\Roaming\npm-cache\_logs\2018-12-14T08_08_29_304Z-debug.log
"Keccak bindings compilation fail. Pure JS implementation will be used."

> scrypt@6.0.3 install C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\scrypt
> node-gyp rebuild


C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\looee\AppData\Local\Programs\Python\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\looee\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\scrypt
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

> secp256k1@3.5.2 install C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\secp256k1
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.5.2 rebuild C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\secp256k1
> node-gyp rebuild


C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\looee\AppData\Local\Programs\Python\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\looee\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\secp256k1
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@3.5.2 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@3.5.2 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\looee\AppData\Roaming\npm-cache\_logs\2018-12-14T08_08_31_427Z-debug.log
"Secp256k1 bindings compilation fail. Pure JS implementation will be used."

> sha3@1.2.2 install C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\sha3
> node-gyp rebuild


C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\sha3>if not defined npm_config_node_gyp (node "C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\looee\AppData\Local\Programs\Python\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\looee\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\looee\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\looee\AppData\Roaming\npm\node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\sha3
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 (node_modules\dav-cli\node_modules\ganache-cli\node_modules\ganache-core\node_modules\scrypt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sha3@1.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sha3@1.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\looee\AppData\Roaming\npm-cache\_logs\2018-12-14
```

Wading through that, it seems like the install exits when trying to install  `sha3@1.2.2`.

## Possible Solution

A workaround is to use [Bash for windows](https://docs.microsoft.com/en-us/windows/wsl/install-win10), the install works fine there. 

Otherwise, it will be necessary to triage this and figure out which packages are failing, then see if there are workarounds for windows available. 

I can look into this further, but if supporting Windows is not a priority for this project I should probably spend my time elsewhere instead so let me know 😅 

## Steps to Reproduce (for bugs)
1. run `npm i -g dav-cli` on windows.

## Your Environment

* Version used:Node v9.0.0, NPM 6.1.0
* Environment name and version: Node v9.0.0, NPM 6.1.0
* Operating System and version: Windows 10

**Comment by TalAter** [comment]
Support for Windows is not a priority... especially if it can simply work by using Bash for windows
👍
